version: "1.1"

services:       

# portainer

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - ${PORTAINER_PORT}:9000
    volumes:
      - ${CONFIG_DIR}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

# overseerr

  overseerr:
    container_name: overseerr
    hostname: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=debug
    ports:
      - ${OVERSEERR_PORT}:5055 
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    links:
      - sonarr
      - radarr
      - plex

# prowlarr

  prowlarr:
    container_name: prowlarr
    hostname: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696

      
# sonarr

  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DATA_DIR}:/data
    ports:
      - ${SONARR_PORT}:8989
      
# radarr

  radarr:
    container_name: radarr
    hostname: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DATA_DIR}:/data
      
# readarr 

  readarr:
    container_name: readarr
    hostname: readarr
    image: linuxserver/readarr:develop
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - ${READARR_PORT}:8787
    volumes:
      - ${CONFIG_DIR}/readarr:/config
      - ${DATA_DIR}:/data


# homarr

  homarr:
    container_name: homarr
    hostname: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - ${HOMARR_PORT}:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/homarr:/config


# homepage

  # homepage:
  #   container_name: homepage
  #   hostname: homepage
  #   image: ghcr.io/gethomepage/homepage:latest
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #   ports:
  #     - ${HOMEPAGE_PORT}:3000
  #   volumes:
  #     - ${CONFIG_DIR}/homepage:/config
  #     - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      
# qBitorrent

  qbittorrent:
    container_name: qbittorrent
    hostname: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:8080
      - ${QBITTORRENT_CONNECTION_PORT}:6881
      - ${QBITTORRENT_CONNECTION_PORT}:6881/udp
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}/torrents:/data/torrents
    healthcheck:
      start_period: 15s

# Plex

  plex:
    container_name: plex
    hostname: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    network_mode: host    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
    # ports:   # seems to conflict with "network_mode: host"
    #   - "${PLEX_WEB_PORT}:32400/tcp"
    #   - "1900:1900/udp"
    #   - "3005:3005/udp"
    #   - "5353:5353"
    #   - "8324:8324/tcp"
    #   - "32410:32410/udp"
    #   - "32412:32412/udp"
    #   - "32413:32413/udp"
    #   - "32414:32414/udp"
    #   - "32469:32469/tcp"
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${DATA_DIR}/media:/data/media
      
#tautulli

  tautulli:
    container_name: tautulli
    hostname: tautulli
    image: ghcr.io/tautulli/tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    depends_on: 
      - plex 
    ports:
      - 8181:8181
    volumes:
      - ${CONFIG_DIR}/tautulli:/config

# Watchtower

  # watchtower:
  #   container_name: watchtower
  #   hostname: watchtower
  #   image: containrrr/watchtower
  #   command: --cleanup
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock


